### ISSUE TITLE
It does not compile

### ISSUE THREAD

**Issue by hydrastarmaster** [DavidArmstrong/SiderealPlanets#1]
I tried to compile Example7_Planets. Here is the error:

[...] Arduino\libraries\SiderealPlanets\src/SiderealPlanets.h:163:36: error: expected unqualified-id before numeric constant
  double EclLongitude, EclLatitude, SE, CE, AM, SR, RR, AL;

**Comment by DavidArmstrong** [comment]
Just to verify this, I compiled Example7_Planets in the Arduino IDE version 1.8.15.
![image](https://user-images.githubusercontent.com/288809/130908858-61665592-9eb1-480f-b644-d139ed9aff05.png)
This compiled fine for the Sparkfun Redboard Turbo that I use for testing.  What processor are you compiling this for?  What is the Arduino IDE host OS?  (i.e. Windows 10, Mac, Linux Ubuntu 18.04, etc.)

**Comment by hydrastarmaster** [comment]
Hi Dave,
Here I'm testing on Win 10 with Arduino 1.8.15 (Windows Store 1.8.49.0), Arduino One with CH340. Library in version 1.0.0 as per library manager.
The line of SiderealPlanets.h that gives the error is a declaration of several variables. I split it to spot the bug:
error: expected unqualified-id before numeric constant   double SE;

It seems that SE is somewhat reserved. I changed the name of this variable to SEr, and this way the error disappears.
But still not compiles, because there is another error. I'm going to check it and report.

**Comment by hydrastarmaster** [comment]
The other error:
Arduino\libraries\SiderealPlanets\src\SiderealPlanets.cpp:1172:38: error: expected unqualified-id before 'volatile'
   double PV, LO, LP, OM, CO, IN, SO, SP, Y, PS, PD, CI, RD, LL, RH, L1, L2, EP, BP, A;
 [and the pointer indicates variable SP]
This causes a number of compiler error for variables out of scope.

SP seems to be a reserved name, so I changed it to SPr and now it compiles.

Please check and consider to change SE and SP names in the library with something longer.

**Comment by hydrastarmaster** [comment]
I tried to run it on Arduino One. This is the message:
10:46:09.679 -> Sidereal Planets Functions
10:46:09.679 -> Target board does not handle Real Double numbers! Stopping...

What about this? I tried several combinations:
1) on Arduino One, it compiles but does not execute (see message above)
2) on Arduino Mega2560 it is the same as (1)
3) on Arduino One without the blocking test, the sketch becomes too big to be loaded (and this seems quite strange to me, also because is just a math lib).
4) on Arduino Mega 2560 it loads and runs with this output (please check if it's the same you have on your board):

![image](https://user-images.githubusercontent.com/41840980/130944205-a54b5113-3522-4f83-b21e-4aaf604cebdb.png)

**Comment by DavidArmstrong** [comment]
I've experienced this "variable  collision" before with one of the other libraries that I've done.  Apparently, some kernel developers will make not so wise choices when it comes to variable names, like SP.  (Which probably represents the 'stack pointer' on that processor.)  Anyway, I've gone ahead and changed all of the short private variable names to hopefully avoid this effect.  (Still in testing, before releasing an update on GitHub,)

However, since I don't have every possible processor out there, I can't guarantee the same results on each one.
This goes with the math libraries too.  It's one of the reasons the library insists on using real double numbers.  The test assumes that float and double are different.  If they end up being the same, particularly floats, then it will always fail the 'begin()' function check.  If you know of a processor that has floats as doubles internally, please let me know.

To verify your output, I will quote the same output I obtained from my test system:


Sidereal Planets Functions

Because these calculations are dependent on both time and location,
those values have to be set first.
We can use the decimalDegrees() function to make this easier.
We define:
DST off, time zone = -5
GMT date: May 30, 1984  GMT Time: 00:00:00
Computing Mercury Parameters
Helio Ecliptic Long: -34:46:20.12  ==> -34:46:20.87
Helio Ecliptic Lat: -6:57:5.34  ==> -6:57:5.34
Radius vector: 0.401741  ==> 0.401740793
Distance from Earth: 0.999923  ==> 0.999921491
Geo Ecliptic Long: 45:55:55.89  ==> 45:55:55.75
Geo Ecliptic Lat: -2:47:16.47  ==> -2:47:16.47
RA: 2:57:8.28  ==> 2:57:8.28
Dec: 13:56:8.81  ==> 13:56:8.91

Computing Saturn Parameters
Helio Ecliptic Long: 223:55:33.24  ==> 223:55:33.24
Helio Ecliptic Lat: 2:19:49.17  ==> 2:19:49.16
Radius vector: 9.866205  ==> 9.866204953
Distance from Earth: 8.957211  ==> 8.957210873
Geo Ecliptic Long: 221:11:41.66  ==> 221:11:41.67
Geo Ecliptic Lat: 2:34:1.15  ==> 2:34:1.14
RA: 14:38:19.72  ==> 14:38:19.72
Dec: -12:44:52.50  ==> -12:44:52.66

Computing Uranus Parameters
GMT date: May 23, 1992  GMT Time: 00:00:00
Geo Ecliptic Long: 284:25:28.66  ==> 284:25:28.66
RA: 19:02:51.09  ==> 19:2:51.09
Dec: -23:04:30.68  ==> -23:4:30.82

**Comment by hydrastarmaster** [comment]
Well, the results are good indeed for astronomical purposes. There is a difference just from the 5th decimal, or tenth of seconds, in the right side values. Not planning to use Arduino to pilot my starship, it seems ok. About precision, maybe some improvement can be made sw side for these AVRs, if you consider it important. Surely a space optimization would be appreciated.

**Comment by DavidArmstrong** [comment]
Space optimization is difficult without literally cutting stuff out.  (i.e. dropping some of the planet routines or other unneeded functionality for a specific use case.)  It's a trade-off.  I could have added even more routines, but what I have now seems more than sufficient for most use cases.
By the way, I've created a branch in the repository, with my proposed changes for mitigating this variable conflict on some processors.  If you can, go ahead and test it on the processor that was giving you the variable errors., and please let me know if this resolved the issue.

**Comment by hydrastarmaster** [comment]
(1) Checked the current code. The changes are good, but it needs some more work. An SD declaration is still present to correct. I'm sorry to say that the error persists, for further variables: A, Y, PS, PD, CI, RD, LL, RH, L1, L2, EP, BP. That kind of squeezed nomenclature is not the best choice at all. It would be better to use understandable names for variables. There are many more variables of this kind in the library... better not to validate them one by one :)
(2) Please, for the lib is very big, you should also consider using the F() macro for strings in Serial.print, so to gain some more space.
(3) SiderealPlanets::begin() should always return true. As we have checked previously, the lib works well with Arduino within its specs. AVR float and double variable have the same length, thus floating point calcs precision is guaranteed just up to the 5th decimal, as we have seen. Anyway, it is good enough for common use cases. You really can drop that test. Or, just in case it will ruin your nights :), you can give a check to https://github.com/mmoller2k/Float64 (but I suppose that you hit the board memory limit).

**Comment by DavidArmstrong** [comment]
Well, I did ask for feedback.  Better to make the needed changes now than have to do several releases.  (Upgrading libraries all the time can be a pain, at least for me.)  This will take a few days to do though.

**Comment by DavidArmstrong** [comment]
The only library routine that uses Serial.print is printDegMinSecs(), and that usage is minimal.  The routine is provided as a convenience, and is not required for use by the library.  The majority of Serial.print() use are in the example sketches, not the library.

**Comment by hydrastarmaster** [comment]
I confirm that your last review of the code is perfect for Mega2560. Space usage is:
--> program space: 33486 byte (13%)  <-- you can add many more functions if you want :)
--> global vars: 2724 byte (33%)
Thank you.

**Comment by markh1301** [comment]
Hello David,
Ive tried the Example4_Sun example on a mega2560 and I get massive errors compared to my iPhone/iPad star app. Also my location and a fair dose of common sense tells me something is up with the code. For example I just set time to 28th Jan 2022 with some approx coords (53 latitude N and 0.6 long W) and it returns Sunrise @ 18.09 and Sunset at 02.52
